apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status
  namespace: argocd-build
spec:
  project: default

  source:
    repoURL: https://github.com/yasir227/main.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://172.31.26.12:6443
    namespace: argocd-build

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
